README.md, src/main/java/fr/eql/project1/entities/Category.java, src/main/java/fr/eql/project1/entities/Credentials.java, src/main/java/fr/eql/project1/entities/Proposal.java, src/main/java/fr/eql/project1/entities/Service.java, src/main/java/fr/eql/project1/entities/User.java, src/main/java/fr/eql/webservices/team1/project1/WebSecurityConfig.java, src/main/resources/application.properties
l'appli démarre mais la page ne s'affiche pas sur localhost:8383/hello
=> #1 Lancer Project1Application.java

pom.xml, src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/dao/PrestationRepository.java, src/main/java/fr/eql/teama/catalogue/dao/ProposalRepository.java, src/main/java/fr/eql/teama/catalogue/service/ProposalService.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java, src/main/java/fr/eql/teama/catalogue/service/UserServiceImpl.java
=> CAT-28 Webservices Services CRUD

src/main/java/fr/eql/teama/catalogue/controller/UserController.java, src/main/java/fr/eql/teama/catalogue/dao/UserRepository.java, src/main/java/fr/eql/teama/catalogue/dto/DeleteResponse.java, src/main/java/fr/eql/teama/catalogue/service/UserService.java, src/main/java/fr/eql/teama/catalogue/service/UserServiceImpl.java
=> CAT-29 CRUD utilisateur #29

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/dao/ProposalRepository.java, src/main/java/fr/eql/teama/catalogue/entities/AlreadyExistException.java, src/main/java/fr/eql/teama/catalogue/entities/ProposalException.java, src/main/java/fr/eql/teama/catalogue/entities/UpdateException.java, src/main/java/fr/eql/teama/catalogue/service/ProposalService.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java, src/main/resources/application.properties
=> CAT-35 Gestion des erreurs

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/dao/ProposalRepository.java, src/main/java/fr/eql/teama/catalogue/entities/AlreadyExistException.java, src/main/java/fr/eql/teama/catalogue/entities/Category.java, src/main/java/fr/eql/teama/catalogue/entities/ProposalException.java, src/main/java/fr/eql/teama/catalogue/entities/UpdateException.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/ProposalService.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java, src/main/resources/application.properties
=> Ajout images catégories

src/main/java/fr/eql/teama/catalogue/dto/CategoryDto.java
=> MAJ dtoCategory #40

src/main/java/fr/eql/teama/catalogue/Project1Application.java, src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java
=> CAT-42 Bugfix errors support

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java
=> CAT-42 bugfix

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java
=> CAT-46 addProposal + category

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/controller/UserController.java, src/main/java/fr/eql/teama/catalogue/dao/CredentialsRepository.java, src/main/java/fr/eql/teama/catalogue/dao/ProposalRepository.java, src/main/java/fr/eql/teama/catalogue/dao/UserRepository.java, src/main/java/fr/eql/teama/catalogue/dto/AuthenticateRequestDto.java, src/main/java/fr/eql/teama/catalogue/dto/FullUserDto.java, src/main/java/fr/eql/teama/catalogue/entities/Credentials.java, src/main/java/fr/eql/teama/catalogue/entities/Proposal.java, src/main/java/fr/eql/teama/catalogue/entities/User.java, src/main/java/fr/eql/teama/catalogue/entities/UserRole.java, src/main/java/fr/eql/teama/catalogue/exception/AlreadyExistException.java, src/main/java/fr/eql/teama/catalogue/exception/ProposalException.java, src/main/java/fr/eql/teama/catalogue/exception/RestResponseEntityExceptionHandler.java, src/main/java/fr/eql/teama/catalogue/exception/UpdateException.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/CredentialsService.java, src/main/java/fr/eql/teama/catalogue/service/CredentialsServiceImpl.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java, src/main/java/fr/eql/teama/catalogue/service/UserService.java, src/main/java/fr/eql/teama/catalogue/service/UserServiceImpl.java
=> Ajouter des credentials, création et modification de compte utilisateur

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/dao/ProposalRepository.java, src/main/java/fr/eql/teama/catalogue/dto/ProposalResearchRequest.java, src/main/java/fr/eql/teama/catalogue/dto/ProposalResearchResponse.java, src/main/java/fr/eql/teama/catalogue/service/ProposalResearchService.java, src/main/java/fr/eql/teama/catalogue/service/ProposalResearchServiceImpl.java
=> Recherche par catégorie

src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/CredentialsService.java, src/main/java/fr/eql/teama/catalogue/service/CredentialsServiceImpl.java
password is not hashed yet (digest sha256 not working)
close #51
=> CAT-51 init user with credentials

src/main/java/fr/eql/teama/catalogue/entities/Credentials.java, src/main/java/fr/eql/teama/catalogue/exception/AlreadyExistException.java, src/main/java/fr/eql/teama/catalogue/exception/ProposalException.java, src/main/java/fr/eql/teama/catalogue/exception/RestException.java, src/main/java/fr/eql/teama/catalogue/exception/RestResponseEntityExceptionHandler.java, src/main/java/fr/eql/teama/catalogue/exception/UpdateException.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java
=> Add JsonIgnore, fix NPE for UserRole and fix RuntimeExceptions not printed

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/service/ProposalService.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java
=> CAT-56 myProposals ws

src/main/java/fr/eql/teama/catalogue/Project1Application.java, src/main/java/fr/eql/teama/catalogue/service/GeolocationServiceImpl.java
=> Externalize API keys in a separate (and private) property file

src/main/java/fr/eql/teama/catalogue/controller/PrestationController.java, src/main/java/fr/eql/teama/catalogue/entities/Prestation.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/PrestationService.java, src/main/java/fr/eql/teama/catalogue/service/PrestationServiceImpl.java
=> ws prestation #60

src/main/java/fr/eql/teama/catalogue/controller/PrestationController.java, src/main/java/fr/eql/teama/catalogue/dao/PrestationRepository.java, src/main/java/fr/eql/teama/catalogue/service/PrestationService.java, src/main/java/fr/eql/teama/catalogue/service/PrestationServiceImpl.java
=> CAT-67 getPrestation for connected user

src/main/java/fr/eql/teama/catalogue/controller/PrestationController.java, src/main/java/fr/eql/teama/catalogue/dto/PrestationDto.java, src/main/java/fr/eql/teama/catalogue/service/PrestationService.java, src/main/java/fr/eql/teama/catalogue/service/PrestationServiceImpl.java
=> modif presta ws et ajout presta dto #68

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java
=> CAT-74 addProposal with provider

src/main/java/fr/eql/teama/catalogue/controller/PrestationController.java
=> CAT-79 add feedback

src/main/java/fr/eql/teama/catalogue/dto/ProposalResearchRequest.java, src/main/java/fr/eql/teama/catalogue/entities/Proposal.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/PrestationServiceImpl.java, src/main/java/fr/eql/teama/catalogue/service/ProposalResearchServiceImpl.java, src/main/java/fr/eql/teama/catalogue/service/ProposalServiceImpl.java
=> Add proposal date and order search results by date

src/main/java/fr/eql/teama/catalogue/entities/Prestation.java
=> CAT-84 EAGER bugfix

src/main/java/fr/eql/teama/catalogue/controller/PrestationController.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/PrestationServiceImpl.java
=> Add prestation dates

src/main/java/fr/eql/teama/catalogue/service/UserServiceImpl.java
=> Set image and globalRating to user when creating one

src/main/java/fr/eql/teama/catalogue/controller/PrestationController.java, src/main/java/fr/eql/teama/catalogue/dto/FullUserDto.java, src/main/java/fr/eql/teama/catalogue/entities/User.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/PrestationServiceImpl.java, src/main/java/fr/eql/teama/catalogue/service/UserService.java, src/main/java/fr/eql/teama/catalogue/service/UserServiceImpl.java
=> Mise à jour de la note globale utilisateur

src/main/java/fr/eql/teama/catalogue/controller/LogstashController.java, src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/dto/ConnectedUserDto.java, src/main/java/fr/eql/teama/catalogue/dto/LogProposalDto.java
=> CAT-95 Add missing DTOs

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/service/LogstashService.java
=> CAT-94 bugfix

src/main/java/fr/eql/teama/catalogue/controller/ProposalController.java, src/main/java/fr/eql/teama/catalogue/dto/ConnectedUserDto.java, src/main/java/fr/eql/teama/catalogue/dto/LogProposalDto.java, src/main/java/fr/eql/teama/catalogue/init/InitDataSet.java, src/main/java/fr/eql/teama/catalogue/service/LogstashService.java, src/main/resources/application.properties
=> Send proposals to logstash when inserting test data

logstash.conf, src/main/resources/application.properties
=> CAT-101 Add logstach config file

Jenkinsfile, pom.xml
=> CAT-107 Frist Jenkins pipeline

src/main/java/fr/eql/teama/catalogue/entities/Category.java, src/main/java/fr/eql/teama/catalogue/entities/User.java
=> CAT-110 Modify db columns name to improve elasticsearch
